import openpyxl
import json


class processed_data():
    wb = openpyxl.load_workbook('staticfiles/통합_식품영양성분DB_가공식품_20221011.xlsx')
    sheet1 = wb['20220927']
    rows = sheet1['A2':'CL77770']

    for row in rows:
        processed_dict = {}
        processed_dict['NO'] = row[0].value
        processed_dict['SAMPLE_ID'] = row[1].value
        processed_dict['식품코드'] = row[2].value
        processed_dict['DB군'] = row[3].value
        processed_dict['상용제품'] = row[4].value
        processed_dict['식품명'] = row[5].value
        processed_dict['연도'] = row[6].value
        processed_dict['제조사/유통사'] = row[7].value
        processed_dict['식품대분류'] = row[8].value
        processed_dict['식품상세분류'] = row[9].value
        processed_dict['1회제공량'] = row[10].value
        processed_dict['내용량_단위'] = row[11].value
        processed_dict['총내용량(g)'] = row[12].value
        processed_dict['총내용량(mL)'] = row[13].value
        processed_dict['에너지(㎉)'] = row[14].value
        processed_dict['수분(g)'] = row[15].value
        processed_dict['단백질(g)'] = row[16].value
        processed_dict['지방(g)'] = row[17].value
        processed_dict['탄수화물(g)'] = row[18].value
        processed_dict['총당류(g)'] = row[19].value
        processed_dict['포도당(g)'] = row[20].value
        processed_dict['과당(g)'] = row[21].value
        processed_dict['포도당(g)'] = row[22].value
        processed_dict['과당(g)'] = row[23].value
        processed_dict['당알콜(g)'] = row[24].value
        processed_dict['에리스리톨(g)'] = row[25].value
        processed_dict['총 식이섬유(g)'] = row[26].value
        processed_dict['칼슘(㎎)'] = row[27].value
        processed_dict['철(㎎)'] = row[28].value
        processed_dict['마그네슘(㎎)'] = row[29].value
        processed_dict['인(㎎)'] = row[30].value
        processed_dict['칼륨(㎎)'] = row[31].value
        processed_dict['나트륨(㎎)'] = row[32].value
        processed_dict['아연(㎎)'] = row[33].value
        processed_dict['구리(㎎)'] = row[34].value
        processed_dict['구리(㎍)'] = row[35].value
        processed_dict['망간(㎎)'] = row[36].value
        processed_dict['셀레늄(㎍)'] = row[37].value
        processed_dict['요오드(㎍)'] = row[38].value
        processed_dict['염소(㎎)'] = row[39].value
        processed_dict['비타민 A(㎍ RE)'] = row[40].value
        processed_dict['베타카로틴(㎍)'] = row[41].value
        processed_dict['비타민 D(D2+D3)(㎍)'] = row[42].value
        processed_dict['비타민 D3(㎍)'] = row[43].value
        processed_dict['비타민 D1(㎍)'] = row[44].value
        processed_dict['비타민 E(㎎)'] = row[45].value
        processed_dict['비타민 E(㎎ α-TE)'] = row[46].value
        processed_dict['비타민 K(㎍)'] = row[47].value
        processed_dict['비타민 K1(㎍)'] = row[48].value
        processed_dict['비타민 K2(㎍)'] = row[49].value
        processed_dict['비타민 B1(㎎)'] = row[50].value
        processed_dict['비타민 B1(㎍)'] = row[51].value
        processed_dict['비타민 B2(㎎)'] = row[52].value
        processed_dict['비타민 B2(㎍)'] = row[53].value
        processed_dict['나이아신(㎎ NE)'] = row[54].value
        processed_dict['판토텐산(㎎)'] = row[55].value
        processed_dict['판토텐산(㎍)'] = row[56].value
        processed_dict['비타민 B6(㎎)'] = row[57].value
        processed_dict['비타민 B6(㎍)'] = row[58].value
        processed_dict['비오틴(㎍)'] = row[59].value
        processed_dict['엽산(DFE)(㎍)'] = row[60].value
        processed_dict['비타민 B12(㎎)'] = row[61].value
        processed_dict['비타민 B12(㎍)'] = row[62].value
        processed_dict['비타민 C(g)'] = row[63].value
        processed_dict['비타민 C(㎎)'] = row[64].value
        processed_dict['콜린(㎎)'] = row[65].value
        processed_dict['류신(㎎)'] = row[66].value
        processed_dict['트립토판(㎎)'] = row[67].value
        processed_dict['히스티딘(㎎)'] = row[68].value
        processed_dict['아르기닌(㎎)'] = row[69].value
        processed_dict['시스테인(㎎)'] = row[70].value
        processed_dict['프롤린(㎎)'] = row[71].value
        processed_dict['타우린(㎎)'] = row[72].value
        processed_dict['콜레스테롤(g)'] = row[73].value
        processed_dict['콜레스테롤(㎎)'] = row[74].value
        processed_dict['총 포화 지방산(g)'] = row[75].value
        processed_dict['리놀레산(18:2(n-6)c)(g)'] = row[76].value
        processed_dict['알파 리놀렌산(18:3(n-3))(㎎)'] = row[77].value
        processed_dict['감마 리놀렌산(18:3(n-6))(㎎)'] = row[78].value
        processed_dict['아라키돈산(20:4(n-6))(㎎)'] = row[79].value
        processed_dict['에이코사펜타에노산(20:5(n-3))(㎎)'] = row[80].value
        processed_dict['도코사헥사에노산(22:6(n-3))(㎎)'] = row[81].value
        processed_dict['EPA와 DHA의 합(㎎)'] = row[82].value
        processed_dict['오메가 3 지방산(g)'] = row[83].value
        processed_dict['트랜스 지방산(g)'] = row[84].value
        processed_dict['총 불포화지방산(g)'] = row[85].value
        processed_dict['회분(g)'] = row[86].value
        processed_dict['카페인(㎎)'] = row[87].value
        processed_dict['성분표출처'] = row[88].value
        processed_dict['발행기관'] = row[89].value
        processed_object = json.dumps(processed_dict, ensure_ascii=False)
