import openpyxl


class agriculture_data():
    wb = openpyxl.load_workbook('staticfiles/통합_식품영양성분DB_농축산물_20221011.xlsx')
    sheet1 = wb['Sheet1']
    rows = sheet1['A2':'EP3271']

    for row in rows:
        agriculture_dict = {}
        agriculture_dict['NO'] = row[0].value
        agriculture_dict['SAMPLE_ID'] = row[1].value
        agriculture_dict['식품코드'] = row[2].value
        agriculture_dict['DB군'] = row[3].value
        agriculture_dict['상용제품'] = row[4].value
        agriculture_dict['식품명'] = row[5].value
        agriculture_dict['연도'] = row[6].value
        agriculture_dict['지역/제조사'] = row[7].value
        agriculture_dict['채취시기'] = row[8].value
        agriculture_dict['식품대분류'] = row[9].value
        agriculture_dict['식품상세분류'] = row[10].value
        agriculture_dict['1회제공량'] = row[11].value
        agriculture_dict['내용량_단위'] = row[12].value
        agriculture_dict['에너지(kcal)'] = row[13].value
        agriculture_dict['수분(g)'] = row[14].value
        agriculture_dict['단백질(g)'] = row[15].value
        agriculture_dict['지방(g)'] = row[16].value
        agriculture_dict['회분(g)'] = row[17].value
        agriculture_dict['탄수화물(g)'] = row[18].value
        agriculture_dict['총당류(g)'] = row[19].value
        agriculture_dict['자당(g)'] = row[20].value
        agriculture_dict['포도당(g)'] = row[21].value
        agriculture_dict['과당(g)'] = row[22].value
        agriculture_dict['유당(g)'] = row[23].value
        agriculture_dict['맥아당(g)'] = row[24].value
        agriculture_dict['갈락토오스(g)'] = row[25].value
        agriculture_dict['총 식이섬유(g)'] = row[26].value
        agriculture_dict['수용성 식이섬유(g)'] = row[27].value
        agriculture_dict['불용성 식이섬유(g)'] = row[28].value
        agriculture_dict['칼슘(mg)'] = row[29].value
        agriculture_dict['철(mg)'] = row[30].value
        agriculture_dict['마그네슘(mg)'] = row[31].value
        agriculture_dict['인(mg)'] = row[32].value
        agriculture_dict['칼륨(mg)'] = row[33].value
        agriculture_dict['나트륨(mg)'] = row[34].value
        agriculture_dict['아연(mg)'] = row[35].value
        agriculture_dict['구리(mg)'] = row[36].value
        agriculture_dict['망간(mg)'] = row[37].value
        agriculture_dict['셀레늄(μg)'] = row[38].value
        agriculture_dict['몰리브덴(μg)'] = row[39].value
        agriculture_dict['요오드(μg)'] = row[40].value
        agriculture_dict['비타민 A(μg)'] = row[41].value
        agriculture_dict['레티놀(μg)'] = row[42].value
        agriculture_dict['베타카로틴(μg)'] = row[43].value
        agriculture_dict['비타민 B1(mg)'] = row[44].value
        agriculture_dict['비타민 B2(mg)'] = row[45].value
        agriculture_dict['나이아신(mg)'] = row[46].value
        agriculture_dict['나이아신(NE)(mg)'] = row[47].value
        agriculture_dict['니코틴산 (mg)'] = row[48].value
        agriculture_dict['니코틴아마이드(mg)'] = row[49].value
        agriculture_dict['판토텐산(mg)'] = row[50].value
        agriculture_dict['비타민 B6(mg)'] = row[51].value
        agriculture_dict['피리독신(mg)'] = row[52].value
        agriculture_dict['비오틴(μg)'] = row[53].value
        agriculture_dict['엽산(DFE)(μg)'] = row[54].value
        agriculture_dict['엽산 - 천연 엽산(μg)'] = row[55].value
        agriculture_dict['엽산 - 합성 엽산(μg)'] = row[56].value
        agriculture_dict['비타민 B12(μg)'] = row[57].value
        agriculture_dict['비타민 C(mg)'] = row[58].value
        agriculture_dict['비타민 D(D2+D3)(μg)'] = row[59].value
        agriculture_dict['비타민 D2(μg)'] = row[60].value
        agriculture_dict['비타민 D3(μg)'] = row[61].value
        agriculture_dict['비타민 E(mg)'] = row[62].value
        agriculture_dict['알파 토코페롤(mg)'] = row[63].value
        agriculture_dict['베타 토코페롤(mg)'] = row[64].value
        agriculture_dict['감마 토코페롤(mg)'] = row[65].value
        agriculture_dict['델타 토코페롤(mg)'] = row[66].value
        agriculture_dict['알파 토코트리에놀(mg)'] = row[67].value
        agriculture_dict['베타 토코트리에놀(mg)'] = row[68].value
        agriculture_dict['감마 토코트리에놀(mg)'] = row[69].value
        agriculture_dict['델타 토코트리에놀(mg)'] = row[70].value
        agriculture_dict['비타민 K(μg)'] = row[71].value
        agriculture_dict['비타민 K1(μg)'] = row[72].value
        agriculture_dict['비타민 K2(μg)'] = row[73].value
        agriculture_dict['총 아미노산(mg)'] = row[74].value
        agriculture_dict['필수 아미노산(mg)'] = row[75].value
        agriculture_dict['이소류신(mg)'] = row[76].value
        agriculture_dict['류신(mg)'] = row[77].value
        agriculture_dict['라이신(mg)'] = row[78].value
        agriculture_dict['메티오닌(mg)'] = row[79].value
        agriculture_dict['페닐알라닌(mg)'] = row[80].value
        agriculture_dict['트레오닌(mg)'] = row[81].value
        agriculture_dict['트립토판(mg)'] = row[82].value
        agriculture_dict['발린(mg)'] = row[83].value
        agriculture_dict['히스티딘(mg)'] = row[84].value
        agriculture_dict['아르기닌(mg)'] = row[85].value
        agriculture_dict['티로신(mg)'] = row[86].value
        agriculture_dict['시스테인(mg)'] = row[87].value
        agriculture_dict['알라닌(mg)'] = row[88].value
        agriculture_dict['아스파르트산(mg)'] = row[89].value
        agriculture_dict['글루탐산(mg)'] = row[90].value
        agriculture_dict['글리신(mg)'] = row[91].value
        agriculture_dict['프롤린(mg)'] = row[92].value
        agriculture_dict['세린(mg)'] = row[93].value
        agriculture_dict['타우린(mg)'] = row[94].value
        agriculture_dict['콜레스테롤(mg)'] = row[95].value
        agriculture_dict['총 지방산(g)'] = row[96].value
        agriculture_dict['총 필수 지방산(g)'] = row[97].value
        agriculture_dict['총 포화 지방산(g)'] = row[98].value
        agriculture_dict['부티르산(4:0)(mg)'] = row[99].value
        agriculture_dict['카프로산(6:0)(mg)'] = row[100].value
        agriculture_dict['카프릴산(8:0)(mg)'] = row[101].value
        agriculture_dict['카프르산(10:0)(mg)'] = row[102].value
        agriculture_dict['라우르산(12:0)(mg)'] = row[103].value
        agriculture_dict['트라이데칸산(13:0)(mg)'] = row[104].value
        agriculture_dict['미리스트산(14:0)(mg)'] = row[105].value
        agriculture_dict['펜타데칸산(15:0)(mg)'] = row[106].value
        agriculture_dict['팔미트산(16:0)(mg)'] = row[107].value
        agriculture_dict['헵타데칸산(17:0)(mg)'] = row[108].value
        agriculture_dict['스테아르산(18:0)(mg)'] = row[109].value
        agriculture_dict['아라키드산(20:0)(mg)'] = row[110].value
        agriculture_dict['헨에이코산산(21:0)(mg)'] = row[111].value
        agriculture_dict['베헨산(22:0)(mg)'] = row[112].value
        agriculture_dict['트리코산산(23:0)(mg)'] = row[113].value
        agriculture_dict['리그노세르산(24:0)(mg)'] = row[114].value
        agriculture_dict['총 불포화지방산(g)'] = row[115].value
        agriculture_dict['총 단일 불포화지방산(g)'] = row[116].value
        agriculture_dict['미리스톨레산(14:1)(mg)'] = row[117].value
        agriculture_dict['팔미톨레산(16:1)(mg)'] = row[118].value
        agriculture_dict['헵타데센산(17:1)(mg)'] = row[119].value
        agriculture_dict['올레산(18:1(n-9))(mg)'] = row[120].value
        agriculture_dict['박센산(18:1(n-7))(mg)'] = row[121].value
        agriculture_dict['가돌레산(20:1)(mg)'] = row[122].value
        agriculture_dict['에루크산(22:1)(mg)'] = row[123].value
        agriculture_dict['네르본산(24:1)(mg)'] = row[124].value
        agriculture_dict['총 다중 불포화지방산(g)'] = row[125].value
        agriculture_dict['리놀레산(18:2(n-6)c)(mg)'] = row[126].value
        agriculture_dict['알파 리놀렌산(18:3(n-3))(mg)'] = row[127].value
        agriculture_dict['감마 리놀렌산(18:3(n-6))(mg)'] = row[128].value
        agriculture_dict['에이코사디에노산(20:2(n-6))(mg)'] = row[129].value
        agriculture_dict['에이코사트리에노산(20:3(n-3))(mg)'] = row[130].value
        agriculture_dict['아라키돈산(20:4(n-6))(mg)'] = row[131].value
        agriculture_dict['에이코사펜타에노산(20:5(n-3))(mg)'] = row[132].value
        agriculture_dict['도코사디에노산(22:2)(mg)'] = row[133].value
        agriculture_dict['도코사펜타에노산(22:5(n-3))(mg)'] = row[134].value
        agriculture_dict['도코사헥사에노산(22:6(n-3))(mg)'] = row[135].value
        agriculture_dict['오메가 3 지방산(g)'] = row[136].value
        agriculture_dict['오메가 6 지방산(g)'] = row[137].value
        agriculture_dict['트랜스 지방산(g)'] = row[138].value
        agriculture_dict['트랜스 올레산(18:1(n-9)t)(mg)'] = row[139].value
        agriculture_dict['트랜스 리놀레산 (18:2t)(mg)'] = row[140].value
        agriculture_dict['트랜스 리놀렌산(18:3t)(mg)'] = row[141].value
        agriculture_dict['식염상당량(g)'] = row[142].value
        agriculture_dict['폐기율(%)'] = row[143].value
        agriculture_dict['출처'] = row[144].value
        agriculture_dict['발행기관'] = row[145].value
        
        
        
        
        

