import openpyxl


class food_data():
    wb = openpyxl.load_workbook('staticfiles/통합_식품영양성분DB_음식_20221011.xlsx')
    sheet1 = wb['Sheet1']
    rows = sheet1['A5':'CV7708']

    for row in rows:
        food_dict = {}
        food_dict['NO'] = row[0].value
        food_dict['SAMPLE_ID'] = row[1].value
        food_dict['식품코드'] = row[2].value
        food_dict['DB군'] = row[3].value
        food_dict['상용제품'] = row[4].value
        food_dict['식품명'] = row[5].value
        food_dict['연도'] = row[6].value
        food_dict['지역/제조사'] = row[7].value
        food_dict['채취시기'] = row[8].value
        food_dict['식품대분류'] = row[9].value
        food_dict['식품상세분류'] = row[10].value
        food_dict['1회제공량'] = row[11].value
        food_dict['내용량_단위'] = row[12].value
        food_dict['총내용량(g)'] = row[13].value
        food_dict['총내용량(mL)'] = row[14].value
        food_dict['에너지(㎉)'] = row[15].value
        food_dict['수분(g)'] = row[16].value
        food_dict['단백질(g)'] = row[17].value
        food_dict['지방(g)'] = row[18].value
        food_dict['탄수화물(g)'] = row[19].value
        food_dict['총당류(g)'] = row[20].value
        food_dict['자당(g)'] = row[21].value
        food_dict['포도당(g)'] = row[22].value
        food_dict['과당(g)'] = row[23].value
        food_dict['유당(g)'] = row[24].value
        food_dict['맥아당(g)'] = row[25].value
        food_dict['총 식이섬유(g)'] = row[26].value
        food_dict['칼슘(㎎)'] = row[27].value
        food_dict['철(㎎)'] = row[28].value
        food_dict['철(㎍)'] = row[29].value
        food_dict['마그네슘(㎎)'] = row[30].value
        food_dict['인(㎎)'] = row[31].value
        food_dict['칼륨(㎎)'] = row[32].value
        food_dict['나트륨(㎎)'] = row[33].value
        food_dict['아연(㎎)'] = row[34].value
        food_dict['구리(㎎)'] = row[35].value
        food_dict['망간(㎎)'] = row[36].value
        food_dict['셀레늄(㎍)'] = row[37].value
        food_dict['레티놀(㎍)'] = row[38].value
        food_dict['베타카로틴(㎍)'] = row[39].value
        food_dict['비타민 D3(㎍)'] = row[40].value
        food_dict['토코페롤(㎎)'] = row[41].value
        food_dict['토코트리에놀(㎎)'] = row[42].value
        food_dict['비타민 B1(㎎)'] = row[43].value
        food_dict['비타민 B2(㎎)'] = row[44].value
        food_dict['나이아신(㎎)'] = row[45].value
        food_dict['엽산(DFE)(㎍)'] = row[46].value
        food_dict['비타민 B12(㎍)'] = row[47].value
        food_dict['비타민 C(㎎)'] = row[48].value
        food_dict['총 아미노산(㎎)'] = row[49].value
        food_dict['이소류신(㎎)'] = row[50].value
        food_dict['류신(㎎)'] = row[51].value
        food_dict['라이신(㎎)'] = row[52].value
        food_dict['메티오닌(㎎)'] = row[53].value
        food_dict['페닐알라닌(㎎)'] = row[54].value
        food_dict['트레오닌(㎎)'] = row[55].value
        food_dict['발린(㎎)'] = row[56].value
        food_dict['히스티딘(㎎)'] = row[57].value
        food_dict['아르기닌(㎎)'] = row[58].value
        food_dict['티로신(㎎)'] = row[59].value
        food_dict['시스테인(㎎)'] = row[60].value
        food_dict['알라닌(㎎)'] = row[61].value
        food_dict['아스파르트산(㎎)'] = row[62].value
        food_dict['글루탐산(㎎)'] = row[63].value
        food_dict['글리신(㎎)'] = row[64].value
        food_dict['프롤린(㎎)'] = row[65].value
        food_dict['세린(㎎)'] = row[66].value
        food_dict['콜레스테롤(㎎)'] = row[67].value
        food_dict['총 포화 지방산(g)'] = row[68].value
        food_dict['부티르산(4:0)(g)'] = row[69].value
        food_dict['카프로산(6:0)(g)'] = row[70].value
        food_dict['카프릴산(8:0)(g)'] = row[71].value
        food_dict['카프르산(10:0)(g)'] = row[72].value
        food_dict['라우르산(12:0)(g)'] = row[73].value
        food_dict['미리스트산(14:0)(g)'] = row[74].value
        food_dict['팔미트산(16:0)(g)'] = row[75].value
        food_dict['스테아르산(18:0)(g)'] = row[76].value
        food_dict['아라키드산(20:0)(g)'] = row[77].value
        food_dict['미리스톨레산(14:1)(g)'] = row[78].value
        food_dict['팔미톨레산(16:1)(g)'] = row[79].value
        food_dict['올레산(18:1(n-9))(g)'] = row[80].value
        food_dict['박센산(18:1(n-7))(g)'] = row[81].value
        food_dict['가돌레산(20:1)(g)'] = row[82].value
        food_dict['리놀레산(18:2(n-6)c)(g)'] = row[83].value
        food_dict['알파 리놀렌산(18:3(n-3))(g)'] = row[84].value
        food_dict['감마 리놀렌산(18:3(n-6))(g)'] = row[85].value
        food_dict['에이코사디에노산(20:2(n-6))(g)'] = row[86].value
        food_dict['에이코사트리에노산(20:3(n-6))(g)'] = row[87].value
        food_dict['아라키돈산(20:4(n-6))(g)'] = row[88].value
        food_dict['에이코사펜타에노산(20:5(n-3))(g)'] = row[89].value
        food_dict['도코사펜타에노산(22:5(n-3))(g)'] = row[90].value
        food_dict['도코사헥사에노산(22:6(n-3))(g)'] = row[91].value
        food_dict['트랜스 지방산(g)'] = row[92].value
        food_dict['트랜스 올레산(18:1(n-9)t)(g)'] = row[93].value
        food_dict['트랜스 리놀레산 (18:2t)(g)'] = row[94].value
        food_dict['트랜스 리놀렌산(18:3t)(g)'] = row[95].value
        food_dict['회분(g)'] = row[96].value
        food_dict['카페인(㎎)'] = row[97].value
        food_dict['성분표출처'] = row[98].value
        food_dict['발행기관'] = row[99].value